#Usage:
#  $ ansible-playbook playbook-install-datadog.yaml -e "RUNTIME_VAR_DATADOG_API_KEY=2dd894f5******0c73474d48f" -e "RUNTIME_VAR_HOSTS=localhost"

- name: Install Datadog Agent on servers in AWS
  hosts: "{{ RUNTIME_VAR_HOSTS }}"
  become: yes
  roles:
    - { role: datadog-agent, become: yes }
  vars:
    datadog_api_key: "{{ RUNTIME_VAR_DATADOG_API_KEY }}"
    datadog_config:
      tags:
        - env:dev
      logs_enabled: true
      process_config:
        enabled: "true"