apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  MONGO_PASSWORD: cGFzc3dvcmQ=
  MONGO_USERNAME: cm9vdA==
  mongodb-replica-set-key: a2V5MTIz
  mongodb-root-password: cGFzc3dvcmQ=