version: "3.7"
services:
  #  caddy_service:
  #    # include base-docker-compose-vars
  #    restart: unless-stopped
  #
  #    container_name: caddy_jenkins
  #    image: caddy:2.2.1
  #    #    environment:
  #    #      - "ACME_AGREE=true"
  #    volumes:
  #      - /tmp/opt/jenkins/config/data:/data/caddy
  #      - /tmp/opt/jenkins/config/Caddyfile:/etc/caddy/Caddyfile
  #    depends_on:
  #      - jenkins_service
  #    ports:
  #      - '80:80'
  #      - '443:443'
  #    links:
  #      - jenkins_service

  jenkins_service:
    restart: unless-stopped
    image: jenkins/jenkins:lts
    container_name: jenkins_dev
    environment:
      - "JAVA_OPTS=-Djava.awt.headless=true
         -Dhudson.footerURL=https://acme.com
         -Xmx196m
         -Djava.io.tmpdir=/tmp/jenkins
         -XX:+UseG1GC
         -XX:MaxGCPauseMillis=400
         -XX:+ParallelRefProcEnabled
         -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
         -XX:+UnlockDiagnosticVMOptions
         -XX:G1SummarizeRSetStatsPeriod=1
         -XX:MaxMetaspaceExpansion=128M
         -Dhudson.DNSMultiCast.disabled=true
         -Dorg.eclipse.jetty.server.Request.maxFormContentSize=51000000"
      - "JENKINS_HOME=/var/lib/jenkins"
      - "JENKINS_SLAVE_AGENT_PORT=50001"
      - "JENKINS_OPTS=--httpPort=6999"
# -Djava.util.logging.config.file=/var/config/jenkins/log.properties
    volumes:
      - ./config:/tmp/jenkins                 # tmp directory
      - ./config:/var/config/jenkins          # config directory
      - ./lib:/var/lib/jenkins                # data directory i.e. JENKINS_HOME set via environment vars
    ports:
      - 50001:50001
#      - 8080:8080


