version: '3'

services:
  drone:
    container_name: drone
    image: drone/drone:1.0.0-rc.5
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/drone:/data
    restart: always
    env_file:
      - /etc/drone/server.env